// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xcwnxbjrcmkectmxzlud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhjd254YmpyY21rZWN0bXh6bHVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4NjM4MjUsImV4cCI6MjA3NDQzOTgyNX0.iMXvnY4QeKjxRK_zd4HewM3Kt8-iRyyOdn4c-GKROec";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});